FROM ubuntu:20.04

MAINTAINER YAISAN <https://github.com/Yaisan>

LABEL "authors"="Santiago Guzman and Yago Claros"
LABEL description="This is custom Docker Image for \
the Comeet App."

EXPOSE 80/tcp
EXPOSE 443/tcp
EXPOSE 10000/udp
EXPOSE 22/tcp
EXPOSE 3478/udp
EXPOSE 5349/tcp
